default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: missnot_development

test:
  <<: *default
  database: missnot_test

production:
  <<: *default
  database: missnot_production